version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.12
    steps:
    - checkout
    - run: python main.py
    - store_test_results:
        path: ./storage
  test:
    docker:
      - image: cimg/python:3.10.12
    steps:
      - checkout
      - run: python test_main.py
      - store_test_results:
          path: ./storage_test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  